#!/usr/bin/env python3
"""Convert the xAI marketplace catalog into a Codex marketplace catalog.

SOURCE: xAI's original ``.grok-plugin/marketplace.json`` is archived under
``source_docs/xai-original/marketplace.json``.
SOURCE: The Codex marketplace shape and policies follow the checked-in
examples saved under ``source_docs/codex-reference/`` and the public
``openai/plugins`` repository.

Entries whose pinned source exposes only Grok/Cursor layout are converted to
local vendored plugins by ``scripts/vendor_xai_plugins.py`` before this
catalog is generated. This keeps the catalog complete without asking Codex to
interpret a foreign manifest directory.
"""

from __future__ import annotations

import json
from pathlib import Path

SOURCE_CATALOG = Path("source_docs/xai-original/marketplace.json")
OUTPUT_CATALOG = Path(".agents/plugins/marketplace.json")
REPORT = Path("docs/compatibility-report.md")

# Verified from each pinned upstream tree. Claude manifests are accepted by
# the workspace importer; Codex manifests are preferred where available.
SUPPORTED = {
    "vercel",
    "chrome-devtools",
    "cloudflare",
    "superpowers",
    "base44",
    "mongodb",
    "mongodb-atlas",
    "neon",
    "wix",
    "netlify",
    "figma",
    "tinyfish",
    "railway",
    "stripe",
    "sentry",
    "axiom",
    "firecrawl",
    "exa",
    "tavily",
    "pstack",
    "browser-use",
}

VENDORED = {
    "sentry",
    "axiom",
    "firecrawl",
    "exa",
    "tavily",
    "pstack",
    "browser-use",
}

# These entries have an equivalent non-Grok subtree at the same pinned SHA.
PATH_OVERRIDES = {
    "tinyfish": "claude",
    "stripe": "providers/codex/plugin",
}

CATEGORY_MAP = {
    "development": "Developer Tools",
    "deployment": "Deployment",
    "monitoring": "Monitoring",
    "database": "Data & Databases",
    "observability": "Observability",
}


def codex_description(value: str) -> str:
    """Adapt product-specific source copy for the Codex-facing catalog."""
    return (
        value.replace("Grok Build", "Codex")
        .replace("from Grok", "in Codex")
        .replace("for Grok", "for Codex")
        .replace("directly from Grok", "directly in Codex")
    )


def convert_entry(entry: dict) -> dict:
    name = entry["name"]
    converted = {"name": name}
    for key in ("description", "homepage", "keywords", "domains"):
        if key in entry:
            converted[key] = (
                codex_description(entry[key])
                if key == "description"
                else entry[key]
            )

    source = entry["source"]
    if name == "neon" or name in VENDORED:
        converted["source"] = {
            "source": "local",
            "path": f"./external_plugins/{name}",
        }
    else:
        remote = dict(source)
        remote["source"] = "url"
        if name in PATH_OVERRIDES:
            remote["path"] = PATH_OVERRIDES[name]
        converted["source"] = remote

    converted["policy"] = {
        "installation": "AVAILABLE",
        "authentication": "ON_INSTALL",
    }
    category = entry.get("category")
    if category in CATEGORY_MAP:
        converted["category"] = CATEGORY_MAP[category]
    return converted


def main() -> int:
    source = json.loads(SOURCE_CATALOG.read_text(encoding="utf-8"))
    converted = [
        convert_entry(entry)
        for entry in source["plugins"]
        if entry["name"] in SUPPORTED
    ]
    catalog = {
        "name": "xai-compatible",
        "interface": {"displayName": "xAI plugins for Codex"},
        "description": (
            "Codex-compatible catalog adapted from the official xAI marketplace."
        ),
        "owner": {"name": "xAI marketplace community fork"},
        "plugins": converted,
    }
    OUTPUT_CATALOG.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_CATALOG.write_text(
        json.dumps(catalog, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    lines = [
        "# xAI marketplace compatibility report",
        "",
        "Generated by `scripts/convert_xai_catalog.py`.",
        "",
        "## Retained",
        "",
        f"{len(converted)} entries are published in `.agents/plugins/marketplace.json`.",
        "",
        "Remote entries retain the original pinned commit SHA. Stripe and TinyFish "
        "use their verified non-Grok subtrees at the same pinned SHA. The seven "
        "Grok/Cursor-only sources are vendored at their original pinned SHAs and "
        "converted to `.codex-plugin/plugin.json`; Neon is also vendored locally.",
        "",
        "## Vendored conversions",
        "",
    ]
    for name in sorted(VENDORED):
        lines.append(f"- `{name}` — local source under `external_plugins/{name}`.")
    lines.extend(["", "The original xAI catalog remains preserved in `source_docs/xai-original/marketplace.json`.", ""])
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_CATALOG} ({len(converted)} plugins)")
    print(f"Wrote {REPORT}")
    print("Vendored: " + ", ".join(sorted(VENDORED)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
